/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:29:05 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright Â© 2013-2016 by Elias Limneos.
*/

// #import <UIKitCore/UIKitCore-Structs.h>
// #import <UIKitCore/UIButton.h>

@interface UIKeyboardDockItemButton : UIButton {

	CGRect _tapActionRegion;

}

@property (assign,nonatomic) CGRect tapActionRegion;              //@synthesize tapActionRegion=_tapActionRegion - In the implementation block
-(CGRect)titleRectForContentRect:(CGRect)arg1 ;
-(CGRect)imageRectForContentRect:(CGRect)arg1 ;
-(CGRect)rectWithSize:(CGSize)arg1 forContentRect:(CGRect)arg2 ;
-(CGRect)tapActionRegion;
-(void)setTapActionRegion:(CGRect)arg1 ;
@end
