/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:29:05 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright Â© 2013-2016 by Elias Limneos.
*/


// #import <UIKitCore/UIKitCore-Structs.h>
@class NSString, UIImage, UIKeyboardDockItemButton, UIPanGestureRecognizer, UILongPressGestureRecognizer;

@interface UIKeyboardDockItem : NSObject {

	NSString* _identifier;
	NSString* _imageName;
	UIImage* _image;
	UIKeyboardDockItemButton* _button;
	UIPanGestureRecognizer* _panGestureRecognizer;
	UILongPressGestureRecognizer* _longPressGestureRecognizer;
	CGPoint _touchDownPoint;

}

@property (nonatomic,retain) UIKeyboardDockItemButton * button;                                      //@synthesize button=_button - In the implementation block
@property (assign,nonatomic) CGPoint touchDownPoint;                                                 //@synthesize touchDownPoint=_touchDownPoint - In the implementation block
@property (nonatomic,retain) UIPanGestureRecognizer * panGestureRecognizer;                          //@synthesize panGestureRecognizer=_panGestureRecognizer - In the implementation block
@property (nonatomic,retain) UILongPressGestureRecognizer * longPressGestureRecognizer;              //@synthesize longPressGestureRecognizer=_longPressGestureRecognizer - In the implementation block
@property (assign,nonatomic) BOOL active; 
@property (assign,nonatomic) BOOL enabled; 
@property (nonatomic,retain) NSString * identifier;                                                  //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic,retain) NSString * imageName;                                                   //@synthesize imageName=_imageName - In the implementation block
@property (nonatomic,retain) UIImage * image;                                                        //@synthesize image=_image - In the implementation block
@property (nonatomic,readonly) UIKeyboardDockItemButton * view; 
+(id)_standardGlyphColor;
+(id)_darkStyleGlyphColor;
-(UIPanGestureRecognizer *)panGestureRecognizer;
-(UILongPressGestureRecognizer *)longPressGestureRecognizer;
-(BOOL)active;
-(void)setButton:(UIKeyboardDockItemButton *)arg1 ;
-(UIKeyboardDockItemButton *)button;
-(void)setEnabled:(BOOL)arg1 ;
-(UIImage *)image;
-(void)setImageName:(NSString *)arg1 ;
-(id)imageWithRenderConfig:(id)arg1 ;
-(id)initWithImageName:(id)arg1 identifier:(id)arg2 ;
-(CGPoint)touchDownPoint;
-(void)setTouchDownPoint:(CGPoint)arg1 ;
-(BOOL)enabled;
-(void)setImage:(UIImage *)arg1 ;
-(void)setIdentifier:(NSString *)arg1 ;
-(NSString *)identifier;
-(void)setPanGestureRecognizer:(UIPanGestureRecognizer *)arg1 ;
-(void)setActive:(BOOL)arg1 ;
-(void)setLongPressGestureRecognizer:(UILongPressGestureRecognizer *)arg1 ;
-(UIKeyboardDockItemButton *)view;
-(NSString *)imageName;
@end
